name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gcloud:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: feeds
          region: europe-west1
          runtime: python310
          entry_point: main
