on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: setup
      uses: google-github-actions/setup-gcloud@v1

    - id: deploy
      run: >-
        gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }}
          --gen2
          --runtime=python310
          --region=${{ secrets.GCP_REGION }}
          --entry-point=main
          --trigger-http