name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gcloud:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: 'google-github-actions/setup-gcloud@v0'

      - run: 'gcloud functions list'
