name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gcloud:
    runs-on: ubuntu-18.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: '${{ secrets.GCP_FUNCTION_NAME }}'
          region: '${{ secrets.GCP_REGION }}'
          runtime: 'python310'
